import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#767576",
        "on-secondary-container": "#ecfaff",
        "primary-fixed": "#ae8dff",
        "on-tertiary-fixed-variant": "#00377b",
        "secondary-container": "#00687a",
        "secondary-fixed-dim": "#48d4f3",
        primary: "#ba9eff",
        "on-tertiary": "#001e4a",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#4388fd",
        "surface-dim": "#0e0e0f",
        "on-error-container": "#ffb2b9",
        "secondary-fixed": "#65e1ff",
        "inverse-primary": "#6e3bd7",
        "surface-container": "#1a191b",
        "on-tertiary-fixed": "#00163b",
        "error-container": "#a70138",
        "outline-variant": "#484849",
        "primary-container": "#ae8dff",
        "tertiary-fixed-dim": "#73a2ff",
        "surface-tint": "#ba9eff",
        "primary-dim": "#8455ef",
        "on-tertiary-container": "#000311",
        "on-primary-fixed-variant": "#370086",
        error: "#ff6e84",
        "surface-container-highest": "#262627",
        "surface-bright": "#2c2c2d",
        "secondary-dim": "#40ceed",
        "on-background": "#ffffff",
        "primary-fixed-dim": "#a27cff",
        "on-error": "#490013",
        tertiary: "#699cff",
        surface: "#0e0e0f",
        "error-dim": "#d73357",
        "inverse-surface": "#fcf8f9",
        "tertiary-fixed": "#8ab0ff",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed-variant": "#005969",
        "on-secondary": "#004b58",
        "inverse-on-surface": "#565556",
        "on-primary-container": "#2b006e",
        "on-secondary-fixed": "#003a45",
        "on-surface": "#ffffff",
        "on-primary": "#39008c",
        background: "#0e0e0f",
        "tertiary-dim": "#699cff",
        "surface-container-high": "#201f21",
        "surface-variant": "#262627",
        secondary: "#53ddfc",
        "on-surface-variant": "#adaaab",
        "surface-container-low": "#131314",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-fira-code)", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 3s infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        reveal: "reveal 0.8s cubic-bezier(0, 0, 0.2, 1) forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        reveal: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
